### ISSUE TITLE
aria-labelledby not aria-labeledby

### ISSUE THREAD

**Issue by goetsu** [oliverfarrell/accessible-tabs#1]
Hi,

I found a small glitch in your code : 
 el.setAttribute('aria-labeledby', 'tab-' + i);
must be changed to 
 el.setAttribute('aria-labelledby', 'tab-' + i);

**Comment by oliverfarrell** [comment]
@goetsu Good spot. It's been a while since I've done anything with this. It's in need of a rewrite.
